# -*- coding: utf-8 -*-
"""CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-t4qALdPLk2p-0AyT0Mz8SxaN0r6REwU
"""

# ============================================================
# CNN IMAGE RECOGNITION USING TENSORFLOW / KERAS
# Dataset: MNIST - Handwritten Digit Recognition
# ============================================================


# ------------------------------------------------------------
# 1. IMPORT LIBRARIES
# ------------------------------------------------------------

import tensorflow as tf
# TensorFlow: Deep Learning framework used to build and train
# our CNN model.

import numpy as np
# NumPy: Used for numerical operations and arrays.

import matplotlib.pyplot as plt
# Matplotlib: Used to display images and graphs.

from tensorflow.keras import layers, models
# Keras provides easy-to-use tools for building Neural Networks.
# layers -> Conv2D, MaxPooling2D, Dense, Flatten, etc.
# models -> Used to create our CNN model.


# ------------------------------------------------------------
# 2. LOAD MNIST DATASET
# ------------------------------------------------------------

# MNIST contains 70,000 handwritten digit images.
# 60,000 images are used for training.
# 10,000 images are used for testing.
#
# The images contain handwritten digits from 0 to 9.

(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()

print("Training Images :", X_train.shape)
print("Testing Images  :", X_test.shape)


# ------------------------------------------------------------
# 3. DEFINE CLASS NAMES
# ------------------------------------------------------------

class_names = [
    '0', '1', '2', '3', '4',
    '5', '6', '7', '8', '9'
]

# These are the 10 digits that our CNN will recognize.


# ------------------------------------------------------------
# 4. DISPLAY SOME TRAINING IMAGES
# ------------------------------------------------------------

plt.figure(figsize=(10, 6))

for i in range(12):

    plt.subplot(3, 4, i + 1)
    # Creates a 3 x 4 grid for displaying 12 images.

    plt.imshow(X_train[i], cmap='gray')
    # Displays the handwritten digit.
    # cmap='gray' displays the image in grayscale.

    plt.title("Actual: " + class_names[y_train[i]])
    # Displays the correct digit above the image.

    plt.axis('off')
    # Removes X and Y axis.

plt.tight_layout()
plt.show()


# ------------------------------------------------------------
# 5. RESHAPE THE IMAGES
# ------------------------------------------------------------

# MNIST images originally have the shape:
# 28 x 28
#
# CNN expects:
# height x width x channels
#
# Since MNIST is grayscale, it has only 1 channel.
#
# Therefore:
# 28 x 28 -> 28 x 28 x 1

X_train = X_train.reshape(-1, 28, 28, 1)
X_test = X_test.reshape(-1, 28, 28, 1)


# ------------------------------------------------------------
# 6. NORMALIZE PIXEL VALUES
# ------------------------------------------------------------

# Original pixel values are between 0 and 255.
# We convert them into values between 0 and 1.

X_train = X_train / 255.0
X_test = X_test / 255.0

print("Pixel values are now between:",
      X_train.min(), "and", X_train.max())


# ------------------------------------------------------------
# 7. BUILD THE CNN MODEL
# ------------------------------------------------------------

model = models.Sequential([

    # --------------------------------------------------------
    # FIRST CONVOLUTION LAYER
    # --------------------------------------------------------

    layers.Conv2D(
        32,
        (3, 3),
        activation='relu',
        input_shape=(28, 28, 1)
    ),

    # Conv2D:
    # Performs convolution on the image.
    #
    # 32:
    # Number of filters used to detect features.
    #
    # (3,3):
    # Size of each filter/kernel.
    #
    # ReLU:
    # Activation function.
    #
    # input_shape=(28,28,1):
    # 28 x 28 = image size
    # 1 = grayscale channel


    # --------------------------------------------------------
    # FIRST MAX POOLING LAYER
    # --------------------------------------------------------

    layers.MaxPooling2D((2, 2)),

    # MaxPooling reduces the size of the feature map.
    #
    # (2,2):
    # Looks at a 2 x 2 region and keeps the maximum value.


    # --------------------------------------------------------
    # SECOND CONVOLUTION LAYER
    # --------------------------------------------------------

    layers.Conv2D(
        64,
        (3, 3),
        activation='relu'
    ),

    # 64 filters are now used.
    #
    # Earlier layers learn simple features such as edges.
    # Deeper layers learn more complex patterns.


    # --------------------------------------------------------
    # SECOND MAX POOLING LAYER
    # --------------------------------------------------------

    layers.MaxPooling2D((2, 2)),


    # --------------------------------------------------------
    # FLATTEN
    # --------------------------------------------------------

    layers.Flatten(),

    # Flatten converts the feature maps into
    # one long 1D vector.
    #
    # Example:
    # Feature Maps
    #      ↓
    # [1, 2, 3, 4, 5, ...]


    # --------------------------------------------------------
    # DENSE / FULLY CONNECTED LAYER
    # --------------------------------------------------------

    layers.Dense(
        64,
        activation='relu'
    ),

    # Dense layer combines the features extracted by CNN.
    # 64 = number of neurons.


    # --------------------------------------------------------
    # OUTPUT LAYER
    # --------------------------------------------------------

    layers.Dense(
        10,
        activation='softmax'
    )

    # 10 = because we have digits 0 to 9.
    #
    # Softmax converts the output into probabilities.
    #
    # Example:
    #
    # 0 -> 0.01
    # 1 -> 0.02
    # 2 -> 0.95
    # 3 -> 0.01
    #
    # Highest probability becomes the prediction.
])


# Display CNN architecture.
model.summary()


# ------------------------------------------------------------
# 8. COMPILE THE MODEL
# ------------------------------------------------------------

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# optimizer='adam'
# Adam updates the weights during training.
#
# loss='sparse_categorical_crossentropy'
# Measures the difference between actual and predicted class.
#
# metrics=['accuracy']
# Measures how many predictions are correct.


# ------------------------------------------------------------
# 9. TRAIN THE CNN
# ------------------------------------------------------------

print("\n========== TRAINING CNN ==========\n")

history = model.fit(
    X_train,
    y_train,
    epochs=5,
    validation_split=0.1,
    batch_size=128
)

# model.fit() starts the training process.
#
# epochs=5
# The training data is processed 5 times.
#
# validation_split=0.1
# 10% of training data is used for validation.
#
# batch_size=128
# 128 images are processed before updating the weights.


# ------------------------------------------------------------
# 10. EVALUATE THE MODEL
# ------------------------------------------------------------

print("\n========== TESTING CNN ==========\n")

test_loss, test_accuracy = model.evaluate(
    X_test,
    y_test,
    verbose=1
)

print("\nTest Loss     :", test_loss)
print("Test Accuracy :", test_accuracy)


# ------------------------------------------------------------
# 11. PLOT TRAINING ACCURACY
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

plt.plot(
    history.history['accuracy'],
    label='Training Accuracy'
)

plt.plot(
    history.history['val_accuracy'],
    label='Validation Accuracy'
)

plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('CNN Training Accuracy')

plt.legend()
plt.grid(True)
plt.show()

# This graph shows how accuracy changes during training.


# ------------------------------------------------------------
# 12. PLOT TRAINING LOSS
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

plt.plot(
    history.history['loss'],
    label='Training Loss'
)

plt.plot(
    history.history['val_loss'],
    label='Validation Loss'
)

plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('CNN Training Loss')

plt.legend()
plt.grid(True)
plt.show()

# Loss should generally decrease as the CNN learns.


# ------------------------------------------------------------
# 13. MAKE PREDICTIONS
# ------------------------------------------------------------

print("\n========== MAKING PREDICTIONS ==========\n")

predictions = model.predict(X_test)

# model.predict()
# Gives probability for each of the 10 digits
# for every test image.


# ------------------------------------------------------------
# 14. DISPLAY IMAGES WITH PREDICTIONS
# ------------------------------------------------------------

plt.figure(figsize=(12, 8))

for i in range(12):

    plt.subplot(3, 4, i + 1)

    plt.imshow(
        X_test[i].reshape(28, 28),
        cmap='gray'
    )

    # np.argmax() finds the position of
    # the highest probability.

    predicted_class = np.argmax(predictions[i])

    actual_class = y_test[i]

    predicted_name = class_names[predicted_class]
    actual_name = class_names[actual_class]

    plt.title(
        f"Predicted: {predicted_name}\n"
        f"Actual: {actual_name}"
    )

    plt.axis('off')

plt.tight_layout()
plt.show()


# ------------------------------------------------------------
# 15. SHOW PROBABILITIES FOR ONE IMAGE
# ------------------------------------------------------------

index = 10

# Select one test image.

plt.figure(figsize=(5, 5))

plt.imshow(
    X_test[index].reshape(28, 28),
    cmap='gray'
)

plt.axis('off')

predicted_class = np.argmax(predictions[index])

plt.title(
    f"Predicted Digit: {class_names[predicted_class]}"
)

plt.show()


print("\nClass Probabilities:\n")

for i in range(10):

    print(
        f"Digit {class_names[i]} : "
        f"{predictions[index][i] * 100:.2f}%"
    )

# This shows how confident the CNN is
# about each possible digit.


# ------------------------------------------------------------
# 16. FINAL RESULT
# ------------------------------------------------------------

print("\n======================================")
print("       CNN DIGIT RECOGNITION")
print("======================================")

print(
    "Test Accuracy :",
    f"{test_accuracy * 100:.2f}%"
)

print(
    "Example Prediction :",
    class_names[np.argmax(predictions[index])]
)

print("======================================")

# ============================================================
# CNN IMAGE RECOGNITION USING TENSORFLOW / KERAS
# Dataset: CIFAR-10
# ============================================================

# ------------------------------------------------------------
# 1. IMPORT LIBRARIES
# ------------------------------------------------------------

import tensorflow as tf
# TensorFlow: Deep Learning framework used to build and train
# our Neural Network.

import numpy as np
# NumPy: Used for numerical operations and handling arrays.

import matplotlib.pyplot as plt
# Matplotlib: Used to display images and graphs.

from tensorflow.keras import layers, models
# Keras provides easy-to-use layers and model building tools.
# layers -> Conv2D, MaxPooling2D, Dense, Flatten, etc.
# models -> Used to create our Neural Network model.


# ------------------------------------------------------------
# 2. LOAD CIFAR-10 DATASET
# ------------------------------------------------------------

# CIFAR-10 contains 60,000 small colour images
# belonging to 10 different classes.

(X_train, y_train), (X_test, y_test) = tf.keras.datasets.cifar10.load_data()

# X_train -> Images used for training
# y_train -> Correct labels for training images
# X_test  -> Images used for testing
# y_test  -> Correct labels for testing images

print("Training Images :", X_train.shape)
print("Testing Images  :", X_test.shape)


# ------------------------------------------------------------
# 3. DEFINE CLASS NAMES
# ------------------------------------------------------------

class_names = [
    'airplane',
    'automobile',
    'bird',
    'cat',
    'deer',
    'dog',
    'frog',
    'horse',
    'ship',
    'truck'
]

# These are the 10 categories that our CNN will recognize.


# ------------------------------------------------------------
# 4. DISPLAY SOME TRAINING IMAGES
# ------------------------------------------------------------

plt.figure(figsize=(10, 6))

for i in range(12):

    plt.subplot(3, 4, i + 1)
    # Creates a 3 x 4 grid for displaying 12 images.

    plt.imshow(X_train[i])
    # Displays the image.

    plt.title(class_names[y_train[i][0]])
    # Displays the actual class name above the image.

    plt.axis('off')
    # Removes X and Y axis because they are not required for images.

plt.tight_layout()
plt.show()


# ------------------------------------------------------------
# 5. NORMALIZE THE IMAGE PIXELS
# ------------------------------------------------------------

# Pixel values are originally between 0 and 255.
# We convert them to values between 0 and 1.

X_train = X_train / 255.0
X_test = X_test / 255.0

print("Pixel values are now between:",
      X_train.min(), "and", X_train.max())


# ------------------------------------------------------------
# 6. BUILD THE CNN MODEL
# ------------------------------------------------------------

model = models.Sequential([

    # --------------------------------------------------------
    # FIRST CONVOLUTION LAYER
    # --------------------------------------------------------

    layers.Conv2D(
        32,
        (3, 3),
        activation='relu',
        input_shape=(32, 32, 3)
    ),

    # Conv2D:
    # Performs convolution on the image.
    #
    # 32:
    # Number of filters used to detect different features.
    #
    # (3,3):
    # Size of each filter/kernel.
    #
    # relu:
    # Activation function used after convolution.
    #
    # input_shape=(32,32,3):
    # Image size = 32 x 32 pixels
    # 3 = RGB colour channels.


    # --------------------------------------------------------
    # FIRST POOLING LAYER
    # --------------------------------------------------------

    layers.MaxPooling2D((2, 2)),

    # MaxPooling:
    # Reduces the size of the feature map.
    #
    # (2,2):
    # Looks at a 2 x 2 region and keeps the maximum value.


    # --------------------------------------------------------
    # SECOND CONVOLUTION LAYER
    # --------------------------------------------------------

    layers.Conv2D(
        64,
        (3, 3),
        activation='relu'
    ),

    # 64 filters are now used to learn more complex features.
    # Early layers learn simple patterns like edges.
    # Deeper layers can learn more complex shapes.


    # --------------------------------------------------------
    # SECOND POOLING LAYER
    # --------------------------------------------------------

    layers.MaxPooling2D((2, 2)),


    # --------------------------------------------------------
    # THIRD CONVOLUTION LAYER
    # --------------------------------------------------------

    layers.Conv2D(
        64,
        (3, 3),
        activation='relu'
    ),

    # Another convolution layer helps the network
    # learn more complex visual features.


    # --------------------------------------------------------
    # FLATTEN
    # --------------------------------------------------------

    layers.Flatten(),

    # Flatten converts the 2D feature maps into
    # one long 1D vector.
    #
    # Example:
    # Feature Maps -> [1,2,3,4,5,...]
    #
    # This prepares the data for the Dense layer.


    # --------------------------------------------------------
    # FULLY CONNECTED / DENSE LAYER
    # --------------------------------------------------------

    layers.Dense(
        64,
        activation='relu'
    ),

    # Dense layer combines the features extracted by CNN.
    # 64 -> Number of neurons in this layer.


    # --------------------------------------------------------
    # OUTPUT LAYER
    # --------------------------------------------------------

    layers.Dense(
        10,
        activation='softmax'
    )

    # 10 -> Because CIFAR-10 has 10 classes.
    #
    # Softmax converts the outputs into probabilities.
    #
    # Example:
    # Cat       -> 0.80
    # Dog       -> 0.10
    # Horse     -> 0.05
    # etc.
    #
    # Highest probability becomes the prediction.
])

# Display the complete architecture of our CNN.
model.summary()


# ------------------------------------------------------------
# 7. COMPILE THE MODEL
# ------------------------------------------------------------

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# optimizer='adam'
# Adam updates the weights during training.
#
# loss='sparse_categorical_crossentropy'
# Measures how different the prediction is from the
# actual class.
#
# metrics=['accuracy']
# Shows how many predictions are correct.


# ------------------------------------------------------------
# 8. TRAIN THE CNN
# ------------------------------------------------------------

print("\n========== TRAINING CNN ==========\n")

history = model.fit(
    X_train,
    y_train,
    epochs=5,
    validation_split=0.1,
    batch_size=128
)

# model.fit()
# Starts the training process.
#
# epochs=10
# The complete training dataset is processed 10 times.
#
# validation_split=0.1
# 10% of training data is used for validation.
#
# batch_size=64
# The model processes 64 images at a time before updating
# its weights.


# ------------------------------------------------------------
# 9. EVALUATE THE MODEL
# ------------------------------------------------------------

print("\n========== TESTING CNN ==========\n")

test_loss, test_accuracy = model.evaluate(
    X_test,
    y_test,
    verbose=1
)

print("\nTest Loss     :", test_loss)
print("Test Accuracy :", test_accuracy)


# ------------------------------------------------------------
# 10. PLOT TRAINING ACCURACY
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

plt.plot(
    history.history['accuracy'],
    label='Training Accuracy'
)

plt.plot(
    history.history['val_accuracy'],
    label='Validation Accuracy'
)

plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('CNN Training Accuracy')

plt.legend()
plt.grid(True)
plt.show()

# This graph shows how the model's accuracy changes
# as training progresses.


# ------------------------------------------------------------
# 11. PLOT TRAINING LOSS
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

plt.plot(
    history.history['loss'],
    label='Training Loss'
)

plt.plot(
    history.history['val_loss'],
    label='Validation Loss'
)

plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('CNN Training Loss')

plt.legend()
plt.grid(True)
plt.show()

# Loss should generally decrease as the model learns.


# ------------------------------------------------------------
# 12. MAKE PREDICTIONS
# ------------------------------------------------------------

print("\n========== MAKING PREDICTIONS ==========\n")

predictions = model.predict(X_test)

# model.predict()
# Gives the probability for each of the 10 classes
# for every test image.


# ------------------------------------------------------------
# 13. DISPLAY TEST IMAGES WITH PREDICTIONS
# ------------------------------------------------------------

plt.figure(figsize=(12, 8))

for i in range(12):

    plt.subplot(3, 4, i + 1)

    plt.imshow(X_test[i])

    # np.argmax() finds the position of the
    # highest probability.

    predicted_class = np.argmax(predictions[i])

    # Get the actual class from the test label.

    actual_class = y_test[i][0]

    # Convert class number into class name.

    predicted_name = class_names[predicted_class]
    actual_name = class_names[actual_class]

    plt.title(
        f"Predicted: {predicted_name}\nActual: {actual_name}"
    )

    plt.axis('off')

plt.tight_layout()
plt.show()


# ------------------------------------------------------------
# 14. SHOW PROBABILITIES FOR ONE IMAGE
# ------------------------------------------------------------

index = 10

# Select one test image.

plt.figure(figsize=(5, 5))

plt.imshow(X_test[index])

plt.axis('off')

predicted_class = np.argmax(predictions[index])

plt.title(
    f"Predicted: {class_names[predicted_class]}"
)

plt.show()


print("\nClass Probabilities:\n")

for i in range(10):

    print(
        f"{class_names[i]:12s} : "
        f"{predictions[index][i] * 100:.2f}%"
    )

# This shows the probability given by the CNN
# to each of the 10 classes.


# ============================================================
# FINAL RESULT
# ============================================================

print("\n======================================")
print("        CNN IMAGE RECOGNITION")
print("======================================")

print("Test Accuracy :", f"{test_accuracy * 100:.2f}%")

print(
    "Example Prediction :",
    class_names[np.argmax(predictions[index])]
)

print("======================================")